astra_db:
  collection_name: "ecommercedata"

embedding_model:
  provider: "cohere"
  model_name: "embed-english-light-v3.0"

retriever:
  top_k: 10
  search_type: "similarity"

llm:
  groq:
    provider: "groq"
    model_name: "openai/gpt-oss-120b"
    temperature: 0.7
